# Generated by Django 3.2 on 2021-04-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('date_create', models.DateTimeField()),
                ('date_task', models.DateTimeField()),
            ],
        ),
    ]
